private:
  key:
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDFd2AATgLrqQLg
    6SJZcLwHTXpQ+SLh07I0RAirjYT8LGjnc5OcKRfnw1IG5tuJGMZgWZUhlV8/Uswl
    UXZ77wds7MZl4sTwxP8QGDF7HvKKTXsQTFqXGfGE/eS2lbyQkTZNz/PAlSKyjm1Q
    3IflcvLRV6R0YbfcaGHrs9s5tbfUR4i26QLaOpqHKDJzvQ5j4T1L1wUlXOznEWwj
    o93W6OWrmllf3F4+aiImcR/PMenZiqZ+A/EhVz8sdePJgWkhAH+LP4Yom0giLoW/
    wnWMKwKinLoff1NoFUMRdKDSllmn1wHjY12zODmuJ2jBBw3KwG5EqN0q42pMx9zz
    MxHtQpdbAgMBAAECggEBALNouniMaGrkrBDcwLCylKOt6SwYr3CufoKuLZJwihrz
    3nwrrjl7vJR+CdDrfxsYv2Ra//v7Uwadm41sblI74ms81SVM29JFqdhdotdSTtsJ
    en5cYRJYJ+/FHkAl26UdylD4V2bqGRRSA1AsjewSfDtnfauf/QTscctNJilQySy8
    GNUSu0RqGpHqIhjepM2PRWwS9d6jIOamOrj96olydJkEbS/TKu1Clz1IerDkBsRN
    vO4HRfm3S4l+7QcmwaGOmb4DGmFtRL3/yQ3li5HvarLSrfN2ssxwR5dPvMG75cdn
    RtMiJYEB/zHFnSX2IKjpVojHH89I0/Ft9RH68FQqxcECgYEA6MItc+H/aR7hjOPm
    yeJkerRZjVnXQsjsO169ZcjfY47V1mMRdIIKD3i32XtuO8P4vc4MxtElzeye9fj9
    KR48kYTBrgpzoS1i5wSSwVCe30KEIDdD7x6qaH9voQcBhHJPPyTdU1zKwX4neZoQ
    ow0ZOpotxgpiJNy59jQcKbam/9cCgYEA2S8NAPUc06oWVtqS1FxkbiNn/02q4bEm
    8FEXKB/MOamBp/GLRVyP7lu6V0/zux5SPS3VB0uPw7l7r6MZaqivPo7YiptjO1Ix
    KEkjsae9iyJ41ZcKWjIVpAWoUoIchayeFyxF5Db1ZYeDf6na1ptaXcpXJTOFw1jd
    NHHFJBBhxB0CgYEAlgdLiu16V0TLd6gSw8CEqb8EFiN5qBeghWg8xpXiv+Z6mTTE
    NIf5eh2Cy9FOrYFVHOrqu2BmcMR7dernK5DM07NxsAAWpiZ+IJCHE8omjZvvVGCr
    Dj+C8dZqmq3MYZXY1MerTad7HZt2UGBpJuAzid2FcaiRuFb6GuNd39lW7YMCgYBL
    EDsDWLRU59V+wV68LQ69Dlm0YKiuBqd5qd1CDfNs/owEerRzDbHlZSi7YrPPuYQd
    Bwk400HmGOaJ5uoy9ghTq9Vl2pzqdNbuoJDIpzwYqZpv4BtA30yhex8ZHUU0Ylvl
    kHS7ks8v/y1Q42jygZEzF2sVPYB+6ujRZn0HoO3ZdQKBgH12I6XZXlNkdPIZMalm
    SU1NvtlxBHRvHxvayK9nRgvJcEQUJfQMbT+laa5SgfNkHCaJJMLc5p3Bxk7xOPiy
    4yKUh3Im6AjNWviT5RpJmuzVydqMZXD8GRexzwdeBnE40SJe7uf0OyJX9jutCcsb
    VUjm+LLv5y+/2RNx79UGLGIp
    -----END PRIVATE KEY-----

server:
  port: 8888